name: nom_order
description: "Order food from inside the restaurant."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: 0.19.0

  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.1.0
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  cloud_firestore: 5.5.0
  cloud_functions: ^5.0.1
  firebase_core_platform_interface: ^5.0.1
  provider: ^6.0.2
  flutter_staggered_animations: ^1.0.0
  http: ^0.13.4
  shared_preferences: ^2.0.15
  bottom_sheet: ^4.0.4
  percent_indicator: 4.2.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_phoenix: ^1.1.1
  package_info_plus: ^8.0.2
  rive: ^0.13.14
  flutter_material_design_icons: ^1.1.7447
  path_provider: ^2.0.14
  flutter_expanded_tile: ^0.4.0
  font_awesome_flutter: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
  fonts:
    - family: noto
      fonts:
        - asset: assets/fonts/NotoSans.otf